tunnel: eee8e6d3-e2f0-43dd-af18-cf46cdff584b
credentials-file: C:\Users\Mini_PC\.cloudflared\eee8e6d3-e2f0-43dd-af18-cf46cdff584b.json

ingress:
  - hostname: pa.khoury.uk
    path: /webhook/telegram
    service: http://127.0.0.1:8080
  - hostname: khoury.uk
    service: http://127.0.0.1:8080
  - service: http_status:404
